apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  namespace: exercise
  labels:
    app: wordpress
    type: exercise
spec:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 2
  template:
    metadata:
      labels:
        app: wordpress
        type: exercise
    spec:
      containers:
      - image: bitnami/wordpress:latest
        name: wordpress
        env:
          - name: MARIA_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: wordpress-config
                key: mariadb-host
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: root-password
          - name: MYSQL_CLIENT_CREATE_DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: wp-dbname
          - name: MYSQL_CLIENT_CREATE_DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: wp-user
          - name: MYSQL_CLIENT_CREATE_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: wp-password
          - name: WORDPRESS_DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: wp-dbname
          - name: WORDPRESS_DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: wp-user
          - name: WORDPRESS_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: wp-password
          - name: WORDPRESS_USERNAME
            valueFrom:
              secretKeyRef:
                name: wp-credentials
                key: user
          - name: WORDPRESS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wp-credentials
                key: password
          - name: WORDPRESS_BLOG_NAME
            valueFrom:
              configMapKeyRef:
                name: wordpress-config
                key: blog-name
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /wp-login.php
            port: 443
          initialDelaySeconds: 300
          periodSeconds: 30
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /wp-login.php
            port: 443
          initialDelaySeconds: 180
          periodSeconds: 15
